name: ci

on:
  release:
    types: [published]


jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Find tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      -
        name: Build go executable
        run: |
          GOOS=linux GOARCH=arm64 go build -o release/linux/arm64/kaniko-docker ./cmd/kaniko-docker 
      -
        name: Docker Buildx (build,push)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            --tag xedonev/drone-plugin-kaniko-arm:${{ steps.vars.outputs.tag }} \
            --file ./docker/docker/Dockerfile.linux.arm64 ./

